apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: PROMETHEUS
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    uid: LOKI
    url: http://loki:3100

  - name: Tempo
    type: tempo
    access: proxy
    uid: TEMPO
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: LOKI
        mappedTags:
          - key: job
        mapTagNamesEnabled: true
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        tags:
          - key: service.name
      serviceMap:
        datasourceUid: PROMETHEUS
      search:
        hide: false
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
  - name: SEIDRA API
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: SEIDRA_API
    jsonData:
      authenticationType: none
