apiVersion: apps/v1
kind: Deployment
metadata:
  name: seidra-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: seidra-backend
  template:
    metadata:
      labels:
        app: seidra-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}/ultimate-backend:{{ .Values.image.tag }}
          {{- if or .Values.configMap.enabled .Values.secrets.enabled }}
          envFrom:
            {{- if .Values.configMap.enabled }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ .Values.secrets.name }}
            {{- end }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}
