name: Ultimate Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version à publier"
        required: true
      environment:
        description: "Environnement de déploiement"
        required: true
        default: "production"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/ultimate-backend:${{ env.TAG }}
            ghcr.io/${{ github.repository }}/ultimate-backend:latest
          push: true
      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/ultimate-frontend:${{ env.TAG }}
            ghcr.io/${{ github.repository }}/ultimate-frontend:latest
          push: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: SEIDRA Ultimate ${{ env.TAG }}
          body: |
            ✅ Build backend & frontend publiés sur GHCR.
            🚀 Charts Helm disponibles dans deploy/helm.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
