global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: seidra-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000

  - job_name: flower
    metrics_path: /metrics
    static_configs:
      - targets:
          - flower:5555

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets:
          - tempo:3200
